name: "Dev action"
author: "Ishaan Sheikh"
description: "Create a post on Dev for a new release on GitHub"
inputs:
  dev-to-secret:
    description: "Secret Key for Dev.to API"
    required: true
    default: ""
  tags:
    description: "Tags to include with post"
    required: true
    default: ""
outputs:
  url:
    description: "The URL of the new article"
runs:
  using: "node12"
  main: "dist/index.js"
